Page Title: Pyxis Logistics		
		
#Object Definitions		
======================================================================================================================================		
loader:xpath:.//div[@id='laoder3']
mini_loader:xpath://div[@class='loader-ring']
generic_loader:xpath://div[contains(@class,"loader")]
loading:xpath:.//*[contains(text(), 'Loading')]
header_page:xpath:.//h3[contains(text(),'${option}')]
link_siteConfiguration:xpath:.//span[contains(text(),'Site Configuration')]
link_siteConfigMenuOptions:xpath:.//label[@title='${column}']
list_printerNames:xpath:.//button[contains(@id, 'edit')]
list_printerStatus:xpath:.//div[@class='rt-tbody']//div[@class='rt-td'][1]/following-sibling::div[contains(text(),'Active')]
option_showInactive:xpath:.//label[contains(text(),'Show Inactive')]/..//input[@id='toggle']
list_columnHeaders:xpath:(.//div[contains(text(),'${column}')])[1]
record_name:xpath:.//*[contains(text(),'${column}')]
settings_header:xpath://div[contains(@class,'setting-dropdown')]//span[contains(text(),'${header}')]
list_link_text:xpath://li[contains(@class,'dropdown nav-item')]//span[contains(text(),'${fieldName}')]
link_buttons:xpath:.//button[@id='${Column}'][1]
input_searchPrinter:xpath:.//input[@name='search']
input_medicationClass:xpath:.//input[@name='searchFilter']
add_distributor_As_per_productID:xpath://div[contains(text(),'${fieldName}')]/../../../div[6]/span
add_distributor_as_per_productID_at_facility_level:xpath://div[contains(text(),'${fieldName}')]]/../../../div[7]/button
page_editPrinter:xpath:.//div[@class='modal-content']
div_with_text:xpath:.//div[contains(text(),'${fieldName}')]
btn_add:xpath:.//button[@id='add']
popup_add_printer:xpath:.//div[@class='modal-body']//h3
text_add_Computer:xpath:.//h3[text()='${header}']
inp_field_printer:xpath:.//input[@id='${fieldName}']
inp:id:externalSystemName
input_with_type:xpath:.//input[@type='${type}']
remove_item_from_listofitem:xpath://div[contains(text(),'${value}')]/following::div[9]/div/button[@id='remove']
dropdown_printer:xpath:.//label[@for='${fieldName}']/following-sibling::div/select
dropdown_destination:xpath:.//label[@for='${fieldName}']/following-sibling::div//select
destination_dropdown:xpath:.//label[@for='facilityKey']/following-sibling::div/div/select
dropdowns_externalSystem:xpath:.//label[@for='${fieldName}']/following-sibling::div/select
span_facilityName:xpath:.//span[contains(text(), '${facilityName}')]
parent_checkbox_printer:xpath:.//label[@for='${fieldName}']/parent::div/input/../..
chkbox_printer:xpath:.//label[@for='${fieldName}']/parent::div/input
chkbox_computer:xpath:.//label[@for='${fieldName}']/parent::div
checkbox_destination:xpath://div[@class='form-check ']//label[@for='${value}']
updated_timeschedule_on_routingRuleScreen:xpath://div[contains(text(),'${recordName}')]/../../../div[2]/div[2]
updated_dayschedule_on_routingRuleScreen:xpath://div[contains(text(),'${recordName}')]/../../../div[2]/div/span[1]
dropdownoption_printer:xpath:.//label[@for='${fieldName}']/following-sibling::div/select/option
btn_cancel:xpath://button[@id='cancel']
link_edit_of_added_record:xpath:.//button[contains(text(),'${fieldName}')]
link_edit_external_system:xpath:.//button[contains(text(),'${fieldName}')]
link_edit:xpath:.//button[text()='${Name}']
link_edit_distination:xpath://div[contains(text(),'${fieldName}')]/../../../div[4]/button
toggle_active:xpath:.//input[@id='isActive']
popup_add_Computer:xpath:.//div[@class='modal-content']
cancel_button:xpath:.//button[@id='cancel']
yes_button:xpath:.//button[@id='primary']
edit_Isa_Name:xpath:.//input[@name='shortDescriptionText']
popup_message:xpath:.//div[@class='toast-body']
#popup_message:xpath:.//div[contains(text(), 'Success! Changes have been saved.')]
popup_msg1:xpath://div[@class='success toast fade show']
icon_mandatory:xpath:.//label[@for='${fieldName}']/span
dropdown_icon_mandatory:xpath:.//label[@for='${fieldName}']/../span
btn_save:xpath:.//button[@id='save']
btn_add_printer:css:#add
#link_edit:css:#edit
cancel_formulary:xpath://div[@class='modal-content']//button[@id='${fieldID}']
sort_icon:xpath:.//div[@class='rt-resizable-header-content'][text()='${column}']
#text_column:xpath:.//div[@class = 'rt-tr-group']/div/div/div/button[contains(text(), 'Edit')]/../../preceding-sibling::div['${column}']
column_by_number:xpath:.//div[@class = 'rt-tr-group']/div/div/div/button[@name='edit']/../../../div[${num}]
name_column:xpath:.//button[@name='edit']
text_column:xpath:.//button[@name='edit']/../../..//div[${num}]//div[@class='item-description truncate']
link_edit_printer:xpath:.//div[@class='rt-tr-group']/div/div[contains(text(),'${printer_name}')]/following-sibling::div[2]
text_error_msg:xpath:.//span[@class='help-block help-block-fixed']
text_error_msg__field_no:xpath:(.//span[@class='help-block help-block-fixed'])[${fieldNumber}]
text_error_msg_destination:xpath:(.//span[@class='help-block help-block-fixed'])['${fieldNumber}']
#added_printer_name:xpath://button[contains(text(),'${fieldName}')]
added_printer_name:xpath://div[contains(text(),'${fieldName}')]
record_name_btn:xpath:.//button[contains(text(),'${recordname}')]
migration_name_col:xpath://div[text()='${fieldName}']
added_schedule_name:xpath://button[text()='${scheduleName}']
schedule_day:xpath:.//div[@class='modal fade show']//button[4]
schedule_day_new:xpath://button[@class='btn btn-day-toggle mr-10 btn-tertiary'][2]
#updated_schedule_day:xpath:(//div[@class='rt-td'][contains(text(),'${fieldName}')]/../div[4]/div/button)[1]
updated_schedule_day:xpath:.//button[contains(text(),'${fieldName}')]/../../../div[@class='rt-td'][1]/div/button[2][contains(@class,'btn-quaternary')]
schedule_day_all:xpath:.//label[contains(text(), 'Days')]/following::div/div//button[contains(@class,'btn btn-day-toggle mr-10 btn-')]
schedule_day_all_selected:xpath:.//label[contains(text(), 'Days')]/following::div/div//button[contains(@class,'btn btn-day-toggle mr-10 btn-secondary')]
popup_delete_schedule:xpath://div[@class='modal-body']
confirm_delete_button:xpath://button[@id='primary']
link_delete:xpath:.//button[text()='${scheduleName}']/../../..//button[@id='delete']
delete_link_therapeutic:xpath:.//button[contains(text(),'${code}')]/../../../div[5]/div/span/span/button[contains(text(),'Delete')]
popup_add_schedule:xpath:.//h3[@class='mb-24 modal-title']
popup_add_schedule_old:xpath:.//h3[contains(@class, 'mb-24')]
popup_add_external_system:xpath://h3[@class='mb-16 modal-title']
popup_add_external_system_old:xpath://h3[contains(@class, 'mb-16')]
popup_add_facility:xpath:.//h3[contains(@class,'mb-24')]//b
popup_add_external_system:xpath://h3[@class='mb-16']
header_edit_dest:xpath:.//h3/b
edit_screen_heading:xpath:.//div//h3 | .//h3/b
header_edit_item:xpath:.//div[contains(@class, 'item-description truncate') and contains(text(), '${itemName}')]
active_toggle_label:xpath:.//label[contains(text(),'${action}')]
itemlevel_facility:xpath://div[contains(text(),'${facilityName}')]
#active_toggle_label:xpath:.//span[@class='switch']/label[contains(text(),'${action}')]
active_toggle:xpath:.//label[contains(text(),'${action}')]/../input
checkboxes_external_system:xpath://label[@class='form-check-label']
checkboxes_external_sys_verification:xpath://input[@id='${fieldName}']
#div_alert:xpath://ul[contains(@class,'content-start')]/li
div_alert:xpath:.//div[@role='alert']
inp_external_system:xpath://input[@id='externalSystemName']
link_edit_external_system:xpath://button[contains(text(),'${fieldName}')]
add_computer_button:id:add
button:xpath://button[@id='${fieldName}']
button_predfined_uom:xpath://button[contains(text(),'${fieldName}')]
popup_for_add:xpath://div[@class='modal-body']//h3
add_routing_rule_label:xpath://h3[contains(.,'Add Routing Rule')]
ipAddress:id:ipAddress
computerName:id:computerName
macAddress:id:macAddress
drop_new:xpath:.//select[@name='defaultFacilityKey']
tab_link:xpath:.//div[@class='tabs']//a[contains(text(),'${tabName}')]
inp_field_computer:xpath:.//label[@for='${fieldName}']/following-sibling::div['${fieldNumber}']//input
facility_dropdown:xpath:.//label[@for='facilityModelKey']/following-sibling::div/select
checkbox_field:xpath://label[@class='form-check-label'][@for='${fieldName}']/parent::div
all_checkbox:xpath://label[@class='form-check-label'][@for='${fieldName}']
#facilityModelKey:xpath:.//label[@for='${fieldName}']/following-sibling::div/select
facilityModelKey:xpath:.//select[@name='defaultFacilityKey']
save_button:xpath:.//button[@id='save']
computer_radio_button:id:isComputerFlag
mobile_radio_button:id:isMobileFlag
active_toggle_button:id:isActive
use_Scan_checkbox:xpath:.//input[contains(@id,'useScan')]/parent::div[@class='form-check ']
control_carousel_checkbox:xpath:.//input[contains(@id,'controlCaraouselISA')]/parent::div[@class='form-check ']
show_inactive_toggle:xpath:.//span[@class='switch']/input[@id='toggle']
macaddress_text:xpath:.//*[@id="macAddress"]
first_col_data:xpath:(.//div[@class='rt-tbody']//div[@class='item-description truncate'])[${num}]
first_record_of_column:xpath:(.//div[@class='rt-tr-group']/child::div/div[${num}])[1]
action_button:xpath:.//button[contains(@id,'${action}')]
action_button2:xpath:.//button[contains(@id,'${action}') and @name='%{action}']
action_button3:xpath:.//div[@class='add-pick add-popup formulary-addpopup']/div[5]//button[contains(text(),'${fieldName}')]
button_with_id:xpath:.//button[@id='${action}']
button_with_name_count:xpath:(.//button[@name='${action}'])[%{num}]
added_computer_name:xpath:.//button[contains(text(),'${computerName}')]
added_record_div:xpath://div[contains(text(),'${fieldName}')]
search:xpath:.//input[@name='search']
list_computerStatus:xpath:.//div[@class='rt-tbody']//div[@class='rt-td'][2]
required_field_label:xpath://span[@class='mr-64 isabread-col']
facility_on_ISA_Screen:xpath://div[@class='mr-24 fs-16']
facility_ISA:xpath://div[@class='mr-24 fs-16']
radio_button_destination:xpath://input[@id='${fieldName}']
radio_for_click:xpath://input[@id='${fieldName}']/..
dest_dropdown:xpath:.//label[@for='${fieldName}']/../following-sibling::div//select
externalsys_facility_dropdown:xpath:.//label[@for='${fieldName}']//following-sibling::div//select
preffered_contact_facility:xpath:.//label[@for='preferredContactMethodKey']/following-sibling::div/select/option
edit_destination_header:xpath://b[contains(text(),'Edit Destination')]
con:xpath:.//div[@class='form-group undefined']
search_item:xpath:.//input[@name='queueFilter']
add_item_btn_destination:xpath:.//button[@id='add']
search_formulary_destination:xpath:.//input[@name='formularySearch']
#search_item_result:xpath:.//div[@class='rt-tr -odd']
search_item_result:xpath:.//div[@class='add-pick add-popup formulary-addpopup']//div[@class='rt-tr -odd']
added_item_details_destination:xpath:.//div[@class='rt-tr -odd']/div
item_checkbox:xpath:.//label[@for='activeFlag-0']
btn_AddItem_save_close:xpath:.//button[contains(text(),'Save & Close')]
max_order_qty:xpath:.//div[@class='d-flex align-items-baseline destination']/span
item_columns:xpath:.//div[@class='rt-thead -header']
add_item_popup_destination:xpath:.//div[@class='add-pick add-popup formulary-addpopup']
limited_order_qty_checkbox:xpath:.//label[@for='limitedOrderQuantity-0']
max_order_qty_text:xpath:.//input[@id='maximumOrderQuantity-0']
max_order_qty_text:xpath:.//input[@id='maxOrderQuantity-0']
checkbox_item_tab:xpath:.//label[@for='${fieldName}']
checkbox_item_tab1:xpath:.//div[@class='form-check']/following::label[${num}]
package_size:xpath:.//span[@name='packageSize']
enable_split_checkbox:xpath:.//label[@for='enableSplitOrders']
save_btn:xpath:.//button[contains(text(),'${field}')]
cancel_btn_item:xpath:.//button[@class='btn btn-secondary w-88']
remove_button:xpath:.//div[@class='rt-tr -odd']//button[(text()='Remove')]
#first_item:xpath:.//div[@class='rt-tbody']/div['${num}']//div
first_item:xpath:.//div[@class='rt-tr-group']
text_column_destination:xpath:.//div[@class = 'rt-tr-group']/div/div/div/button[contains(text(), 'Remove')]/../../preceding-sibling::div['Item']
disabled_items_note:xpath:.//label[@for='ShowItemNote']
added_hold_reason_name:xpath:.//button[contains(text(),'${holdReasonName}')]
hold_reason_name:xpath:(//div[@class='item-description truncate'])[1]
added_priority:xpath:.//div[contains(text(),'${fieldName}')]
#search:xpath:.//input[@name='search']
search_box:xpath:.//input[@name='${searchFilter}']
action_toggle_button:xpath:.//input[@name='${toggle}']
action_toggle_button_1:xpath:.//label[@for='${toggle}']
settings_flag_facility:xpath:.//label/div/label[@for='${toggle}']
text_column_distributor:xpath:.//div[@class='form-group ']//input[@type='text']
input_field_account_number:xpath:.//input[@id='${field}']
#message_field:xpath:.//div[contains(@class, 'has-error')]//div[2]
link_edit_duplicate_schedule:xpath:.//button[contains(text(),'${Item}')]/../../following-sibling::div//button[text()='%{op}']
link_duplicate_label:xpath:.//button[contains(text(),'${Item}')]/../../div//button[text()='%{op}']
label_action:xpath:.//button[contains(text(),'${Item}')]/../../../div//button[text()='%{op}']
link_edit_dest:xpath:(//button[contains(text(),'${Item}')])[1]
link_edit_duplicate_schedule:xpath:(.//button[contains(text(),'${Item}')]/../../following-sibling::div//button[text()='%{op}'])[1]
page_heading_new:xpath:.//h3[contains(text(),'${field}')]
page_heading:xpath:.//*[contains(text(),'${field}')]
message_field:xpath:.//div[contains(@class,'has-error')]//*[contains(text(),'${command}')]
popup_destinations:xpath:.//div[@class='modal-footer']//button[contains(text(),'${command}')]
added_distributor_name:xpath:.//div[contains(text(),'${distName}')]
text_msg:xpath:.//p[contains(text(),'${text}')]
label_msg:xpath:.//label[contains(text(),'${text}')]
div_table:css:.rt-tr-group
checbox_userName:xpath:.//div[contains(text(),'${Name}')]/..//label
list_userName:xpath:.//div[@class='rt-tr-group']//input[@type='checkbox']/../../following-sibling::div
table_column:xpath:.//div[contains(@class,'header')]/div[text()='${colName}']
parent_column:xpath:.//div[contains(@class,'header')]/div[text()='${colName}']/parent::div
label_chkbox_userName:xpath:.//div[contains(text(),'${Name}')]/parent::div//label[@class='form-check-label']
inp_chkbox_userName:xpath:.//div[contains(text(),'${Name}')]/parent::div//label[@class='form-check-label']/../input
text_input_routingRule:xpath:.//input[@name= 'routingRuleName']
routingrule_expander_btn:xpath:.//button[contains(text(), '${recordName}')]/../../..//div[contains(@class, 'expander')]
link_footer_routingRule:xpath:.//button[@id='${linkName}']
button_routingRule:xpath:.//button[@id='${btnName}']
button_cancel_rotingRule:xpath:.//button[@id='${btnName}']
label_routingRule:xpath:.//label[contains(text(), '${labelText}')]
inputboxRoutingRule:xpath:.//input[@name= 'routingRuleName']
btn_radio_routingrule:xpath:.//input[@name='${linkName}']/../label[@for='%{type}']
btn_radio_routing:xpath:.//input[@name='${linkName}' and @id='%{type}']
#message_field:xpath:.//input[@name= 'routingRuleName']/following-sibling::span
message_field_routing_rule:xpath:.//input[@name= 'routingRuleName']/following-sibling::span
header_title_routingRule:xpath:.//div/h3[@class='d-flex']
page_header_generic:xpath:.//div//h3
link_breadcrumb_routingRule:xpath:.//a[contains(text(), 'Routing Rules')]
popup_message_routingrule:xpath:.//div[@class='toast-body']
header_title_routingRule:xpath:.//h3[@class='mb-24 d-flex']
text_toggleHeader:xpath:.//div[contains(text(), '${text}')]
text_popup_routingRule:xpath:.//span[contains(text(), '${text}')]
priority_2:xpath:.//span[text()='${text}']
input_field:xpath:.//input[contains(@id,'${fieldName}')]
input_field_Formulary_details:xpath:.//div[contains(text(), '${fieldName}')]
input_field_Formulary_details:xpath:.//div[contains(text(), '${fieldName}')]
max_daily_Quantity:xpath:.//span[contains(text(),'Please provide value greater than 0.')]
max_Quantity_default:xpath:.//span[@id='${fieldName}']
textarea_field:xpath:.//textarea[contains(@id,'${fieldName}')]
results:xpath://div[@class='rt-td']//div/button
#(.//div[@class='rt-tbody']//div[@class='item-description truncate'])[${num}]
#//*[contains(@class,'item-description truncate')][text()='PIS']
results_added_record:xpath://*[@class='btn btn-link hover-underline']
results_item:xpath:.//div[@class='rt-tbody']//div[@class='rt-td'][${num}]/div/div
add_preferred_distributor:xpath://span[contains(text(),'${linkText}')]
active_external_systems:xpath://div[@class='rt-td'][${num}]/div
sort_results:xpath:.//div[@class='rt-td columnRightAlign'][${num}]
item_result:xpath:(.//div[@class='rt-tbody']//div[@class='rt-td']/div/div)[1]
first_option:xpath://li[@id='item-id-2_li']//label
txn_priorities_results:xpath:.//span[@class='priorities-name truncate max-w-70-per']/div/div
columns_first_row:xpath:(.//div[@class='rt-tbody']//div[@class='rt-td'][${colNumber}])[1]/div
verification_text:xpath:(.//div[@class='rt-tbody']//div[@class='rt-td'][${colNumber}]/div)[1]
distributor_account_nos:xpath:.//div[@class='rt-tbody']//div[@class='form-group ']/input
toggle_popup:xpath://p[@class='robotoRegular fs-16']
list_destinationNames:xpath:.//button[@name='edit']
List_destinationfacilityNames:xpath:.//div[@class='rt-td'][2]
List_destinationStatus:xpath:.//div[contains(text(),'Active')]
option_destinationshowInactive:xpath:.//input[@id='toggle']
btn_add_destination:xpath://button[@id='add']
searchtextbox_destination:xpath:.//input[@class='form-control w-312']
btn_add_destination:xpath:.//button[@class='btn btn-primary w-88']
link_edit_destination:xpath:.//button[@class='btn btn-link']
facilitydropdown_destination:xpath:.//div[@class='form-group undefined']/select
itemlocation_dropdown:xpath:.//div[@class='form-group undefined']/select[@idfield='${id}']
ColumnName_destination:xpath://div[@class='rt-tr -odd']/div
ColumnFacility_destination:xpath:.//div[contains(text(),'Facility')]
ColumnStatus_destination:xpath:.//div[contains(text(),'Status')]
input_searchDestination:xpath:.//input[@name='search']
siteconfig_breadcrumb_destiantion:xpath:.//a[contains(text(),'Site Configuration')]
text_no_data:xpath:.//div[@class='rt-noData'] 
checkbox_allRadioButton:xpath:.//input[@name='${type}']
routing_rule_name:xpath:.//button[contains(text(),'${ruleName}')]
routing_rule_details:xpath:.//div[contains(text(),'${ruleName}')]/following::div[@class='items'] 
list_deleteAction:xpath:.//button[@name='delete']
routing_priorities_tooltip:xpath:(//div[contains(@class,'rt-tr -')]//h3[contains(text(),'Priorities')][contains(text(),'Priorities')])[1]
routing_destinations_tooltip:xpath:(//h3[contains(text(),'destinations')][contains(text(),'destinations') and not(contains(text(),'0 destinations'))])[1]
list_addAction:xpath:.//button[@name='add']
routing_priorities:xpath:(//div[contains(text(),'Priorities')and not(contains(text(),'0 Priorities'))])[1]
routing_destinations:xpath:(//div[contains(text(),'destinations')and not(contains(text(),'0 destinations'))])[1]
error_message_routingrule:xpath:.//div[@role='alert']/ul/li
breadcrumb_facility:xpath:.//a[contains(text(),'Facility Management')]
edit_routing_rule:xpath:.//button[contains(@id, 'edit')]
list_editAction:xpath:.//div[@class='rt-tbody']//button[@name='edit']
search_routing_rule:xpath:.//input[@id='scheduleSearch']
button_edit_transactionPriority:xpath:.//div[contains(text(), '${text}')]/../../../../../div[13]/button[@name='edit']
facilities_tq_options_header:xpath:.//div[@class='p-24']/div[@class='mb-24 font-weight-bold']
checkbox_tq_options1:xpath://div[text()='${fieldName}']
checkbox_tq_options:xpath:.//label[@for='${fieldName}' and contains(text(),'%{fieldName}')]//div/label
am_buttons:xpath:.//div[@class='am-column d-flex flex-row justify-content-between']/button
pm_buttons:xpath:.//div[@class='pm-column d-flex flex-row justify-content-between']/button
btn:xpath:.//button[contains(@id,'${text}')]
#btn:xpath:.//button[@id='c_pm_button'] //span[contains(text(), '${text}')]
show_items:xpath:.//label[@for='showItems']
cycle_Count_heading:xpath:.//div[contains(text(),'Manage Cycle')]
msg_cycle_count:xpath:.//div[@class='d-flex align-self-end sub-heading']
msg_cycle_count2:xpath:.//div[@class='d-flex align-self-end sub-heading']/span
row_buttons_am:xpath:.//div[@class='am-column d-flex flex-row justify-content-between']/button[contains(@id,'${text}')]
row_buttons_pm:xpath:.//div[@class='pm-column d-flex flex-row justify-content-between']/button[contains(@id,'${text}')]
parent_checkbox_cyclecount:xpath:.//label[@for='${field}']
checkbox_medicationClass:xpath://label[@for='checkboxundefined']/../input
start_am_button:xpath:.//div[@class='am-column d-flex flex-row justify-content-between']/button[1]
end_pm_button:xpath:.//div[@class='pm-column d-flex flex-row justify-content-between']/button[1]
row_buttons:xpath:.//div[contains(text(),'Sun')]/following::div[@class='am-column d-flex flex-row justify-content-between']/button[contains(@id,'${text}')]
popup_add_facility:xpath:.//h3[@class='mb-24']
page_title:xpath://h3[contains(@class,'mb-24')]
link_ISAedit:xpath:.//div[contains(text(),'${text}')]/..//button
cyclecount_calendar:xpath:.//input[contains(@class,'input-date')]
current_month:xpath:.//div[contains(text(),'${text}')]
today_date:xpath:.//div[contains(@class,'react-datepicker__day--today')]
add_btn_cyclecount:xpath:.//button[@id='add_button']
disabled_list:xpath:.//div[@class='date-list d-flex justify-content-between']/div[contains(text(),'${date}')]
remove_btn_cyclecount:xpath:.//div[@class='date-list d-flex justify-content-between']/div/following-sibling::button[@id='remove_button']
label_TransactionPriorities:xpath:.//input[@name = '${activeFlag}']/../label
distributor_account_checkbox:xpath:(.//input[@name = '${activeFlag}']/../label)[1]
header_FacilityTransactionPriority:xpath:.//div[contains(@class, 'rt-resizable-header-content') and text() = '${header}']
textbox_searchTransactionPriority:xpath:.//input[@id='prioritySearch']
text_TransactionPriority:xpath:.//div[@class='rt-tr-group']/div/div[1]
textbox_accountNumberAddFacility:xpath:.//input[@name = 'vendorAccountCode']
textbox_accountNumberAddFacility_Sanity:xpath:.//div[contains(text(),'${name}')]/../../following-sibling::div/div/input[@name='vendorAccountCode']
textbox_accountNumberAddDestination:xpath:.//div[contains(text(),'${name}')]/parent::div//input[@name='vendorAccountNumberText']
facilities_otherfields_options_header:xpath:.//div[contains(@class,'mb-20')]
list_batchwait:xpath:.//input[@name='batchWaitMinutesQuantity']
error_class:xpath:.//div[@class='form-group has-error']
checkbox_columnDistributorAccount:xpath:.//input[@name='${columnName}']/../label
priority_color:xpath://div[@title='${colorCode}']
input_field_by_name:xpath://div[@class='${fieldName}']
#//input[@name='${fieldName}']
input_maxHoldMin:xpath:.//input[@name='maxHoldMinutes']
data_maxHolMin:xpath:.//span[contains(text(), '${fieldName}')]/../../../div[4]/span
list_priorityName:xpath:.//span[@class = 'priorities-name truncate max-w-70-per']
txn_priority_checkboxes:xpath://label[contains(@for,'activeFlag')]
new_txn_priority_record_checkbox:xpath:(//label[contains(@for,'activeFlag')])['${num}']
add_schedule_popup:xpath:.//div[@class='modal-content']//h3[contains(text(),'${feature}')]
add_popup:xpath:.//div[@class='modal-content']
error_schedule_msg:xpath:.//div[@class='modal-body']//div[contains(@class,'alert')]
icon_mandatory_schedule:xpath:.//label[text()='${type}']/span
txn_priority_active_checkboxes:xpath://label[contains(@for,'activeFlag')]
txn_priority_system_checkboxes:xpath://label[contains(@for,'systemFlag')]
new_txn_priority_record_active_checkbox:xpath:(//label[contains(@for,'activeFlag')])[${num}]
new_txn_priority_record_system_checkbox:xpath:(//label[contains(@for,'systemFlag')])[${num}]
new_txn_priority_record_useInterfaceMedName_checkbox:xpath:(//label[contains(@for,'useInterfaceMedNameFlag')])[${num}]
new_txn_priority_record_manualpick_checkbox:xpath:(//label[contains(@for,'forManualPickFlag')])[${num}]
new_txn_priority_record_manualrestock_checkbox:xpath:(//label[contains(@for,'forManualRestockFlag')])[${num}]
checkbox_new:xpath:(//label[contains(@for,'${fieldName}')])[%{rowNumber}]
second_sort:xpath:.//select[@name='${fieldName}']
isa_label_location_assignment:xpath:.//label[@for='isa']
isa_dropdown_location_assignment:xpath:.//select[@name='ISA']
last_element:xpath://div['{num}']//div[1]//div[1]//div[12]
facility_item_level:xpath:(//div[@class='d-flex justify-content-between'])[${num}]
btn_setbulkItem:xpath:.//button[@id='setBulkItem']
bulkItem_popUP:xpath:.//div[@class='modal-header']/h5
bulkitems_numbers:xpath:.//div[@class='rt-tbody']//div[@class='rt-tr-group']
click_checkbox_facilityitem_sanity:xpath:.//div[contains(text(),'${facilityName}')]/..//label
click_checkbox_facilityitem:xpath:(//div[@class='form-check '])[1]/label
click_checkbox_facilityitem1:xpath:(//div[@class='form-check '])[2]/label
click_checkbox_facilityitem2:xpath:(//div[@class='form-check '])[3]/label
click_checkbox_role_uom:xpath:(//div[@class='form-check '])[${num}]/label
action_button1:xpath://button[contains(text(),'${fieldName}')]
get_item_name:xpath://div[contains(text(),'${fieldName}')]
get_Max_Daily_quantity:xpath://div[contains(text(),'${itemName}')]/following::div[10]/span[contains(text(),'—')]
package_size:xpath://span[@id='packageSize-0']
replacement_cost_facility_level:xpath://div[@class='rt-tr -odd']//div[@class='rt-td']//div//input[@id='${fieldID}']
checkbox_participating_facility:xpath://div[contains(text(),'${facilityName}')]/../../../div/div/label
button_enabled:xpath://button[@name='${field}']
#action_button1:xpath://button[@class='w-100 item-actiondropdown dropdown-toggle btn btn-primary']
save_button_enabled:xpath:.//button[@name='${fieldName}']
added_button:xpath:.//button[contains(text(),'${fieldName}')]
add_item_strength_field:xpath://input[@name='strengthAmount']
add_item_fields:xpath://input[@name='${fieldName}']
add_item_dropdowns:xpath:.//select[@name='${fieldName}']
Add_new_item_actions:xpath:.//button[contains(text(),'${fieldName}')]
filter_btn_item:xpath:.//button[@class='funnel badfil mr-24']
filter_items_heading:xpath:.//h5[@class='modal-title']
filter_dropdown:xpath:.//select[@name='${field}']
count_on_filtericon:xpath:.//button[@class='fil badfil mr-24']/span
count_on_filter_location:xpath:.//button[@class='fil badfil']/span
attribute_dropdown_value:xpath:.//select[@name='field']/option[contains(text(),'${field}')]
applyfilter_btn:xpath:.//button[@id='${field}']
dropdown_itemManagement:xpath:.//input[@class='search']
dropdown_itemManagement_options:xpath:.//span[@class='node-label'][contains(text(),'${name}')]
dropdown_MyFacilities_options:xpath:.//label[@title='${name}']/preceding-sibling::i
cross_icon:xpath:.//span[@class='icon-close-bold-sm form-control-clear']
button_SystemLabel:xpath:.//button[(text()='${name}')]
cross_icon:xpath:.//div[@class='input-group mb-2 has-clear search-box']/span
button_SystemLabel:xpath:.//button[contains(text(),'${name}')]
popup_add_systemlabel:xpath://div[@class='modal-content']//h3
ele_add_systemlabel:xpath:.//div[@class='modal-content']//*[contains(text(),'${elementName}')]
newly_added_record_status:xpath:((//div[@class='rt-table']//*[text()='Name']/following::div[@class='rt-tr-group']//div[contains(text(),'${labelName}')])[1]/following::span[text()='%{status}'])[1]
#newly_added_record_status:xpath:.//div[@class='rt-table']//*[text()='Name']/following::div[@class='rt-tr-group']//div[contains(text(),'${labelName}')]/following::div[6]/span[text()='%{status}']
standard_label_status:xpath:((//div[@class='rt-table']//*[text()='Name']/following::div[@class='rt-tr-group']//button[contains(text(),'${labelName}')])[1]/following::span[text()='%{status}'])[1]
priority_select_label:xpath:.//div[@id='priority']//li//label[@title='${priority}']/input[@type='checkbox']
priority_select_label_for:xpath:.//div[@id='priority']//li//label[@title='${priority}']
priority_toggle_label:xpath:.//div[text()='${priority}']/../../../div//label
edit_link_system_label:xpath:.//div[@class='rt-tbody']//button[text()='${link}']
count_assigned_priority:xpath:.//a[contains(text(),'${item}')]/span
checkbox_transaction_priority_system_label:xpath:.//div[text()='${priority}']/following::input[@class='switch']
checkbox_transaction_priority_system_label_for:xpath:.//div[text()='${priority}']/following::input[@class='switch']/following::label
system_label_popup:xpath:.//div[@class='modal-content']//H3
dropdown_transPriority_SystemLabel:xpath:.//label[@for='priority']/following-sibling::div
list_sysLabels:xpath:.//div[@class='rt-tbody']//div[contains(@class,'rt-td')][${num}]
#text_column_systemLabel:xpath:.//div[@class = 'rt-tr-group']/div/div/div/button[contains(text(), 'Edit')]/../../preceding-sibling::div['${column}']['%{index}]']
text_column_systemLabel:xpath:.//div[contains(text(),'${fieldName}')]
dropdown_printer_systemLabel:xpath:.//select[@name='${fieldName}']
tool_tip:xpath://div[contains(@class,'d-inline')]
tool_tip_text:xpath://div[contains(@class,'d-inline')]/span
dropdown_showrows_item:xpath:.//select[@idfield='${fieldName}']
dropdown_icon_item_external:xpath:.(//i[@class='toggle collapsed'])[${num}]
edit_link_item_location:xpath:.//div[@class='rt-tr-group']//div[contains(text(),'${item}')]/following-sibling::div//button
header_location_management:xpath:.//h3[contains(text(),'Item Locations')]
assign_button:xpath://button[@name='assign']
button_unassign_location:xpath:(//button[@id='${fieldID}'])[%{rownum}]
save_button_edit_location:xpath:.//button[@id='primary']
cancel_button_edit_location:xpath:.//button[@id='secondary']
#.//div[contains(@class, 'unavailable')][1]
page_text:xpath:.//span[@class='pagination-text mt-2']
pages_location:xpath:.//div[@class='pagination']
facility_dropdown_edit_location:xpath:.//select[@name='FacilityDropdown']
receivingfacility_dropdown:xpath:.//select[@name='packageSharingFacilityKey']
search_location:xpath:.//div[@class='input-group mb-2 has-clear search-box']
filter_location_btn:xpath:.//button[@class='funnel badfil']
search_location:xpath:.//input[@id='scheduleSearch']
item_id_location:xpath://*[@id="root"]/div/div[2]/div/div[1]/div[3]
facility_location:xpath:.//span[@class='robotoBold ml-20']
popup_assign_location:xpath:.//h3[@class='mb-16']
assign_location_page:xpath:.//div[@class='location-assign']
assign_location_btn:xpath:.//button[@id='assignItem']
slot_location:xpath:.//div[@class='d-flex flex-column-reverse align-content-around justify-content-around flex-wrap h-404']/div[contains(@class,'selected-slot')][1]
quantity:xpath:.//input[@id='${name}']
label_edit_system_label:xpath:.//label[text()='${fieldName}']/following::*[@id='%{fieldType}']
unassign_btn:xpath:.//button[@id='unassign']
edit_button_locationAssignement:xpath:.//button[@id='edit']
unassign_location_popup:xpath:.//div[@class='modal-content']
#:xpath:.//div[@class='modal-content']
unassign_popup_header:xpath:.//div[@class='modal-content']/div/h3
assigned_location_value:xpath:.//div[@class='rt-tr-group']/div
noLocation_message:xpath:.//div[@class='messageBeforeSearch d-flex flex-column justify-content-center align-items-center']/p
myFacility_droddown:xpath:.//select[@name='FacilityDropdown']
search_location:xpath:.//input[@name='search']
filter_dropdown_item:xpath:(.//select[@name='${field}'])[%{rownum}]
preffered_distributor_info:xpath:(//input[contains(@id,'${fieldName}')])[%{rownum}]
preferred_distributor_on_manage_distributor_screen:xpath:(//input[contains(@id,'${fieldName}')])[%{rownum}]/../../../div[2]
manage_distributor_header:xpath://h3[contains(@class,'${className}')]
popup_error:xpath:.//div[@class='toast-body']
dispense_ext_dropdown:xpath:.//select[@name='${type}']
item_management_header:xpath://label[contains(@class,'${className}')]
system_label_list:xpath:.//div[@class="ReactTable"]//div[@class='rt-table']//div[@class='rt-tr-group']
productID:xpath:.//div/label[contains(text(), 'Parsed Product ID')]/../../p
preferred_product_id:xpath://div[contains(text(),'${productID}')]/../../../div/div/input
product_id_button:xpath://a[contains(text(),'${fieldName}')]
toggle_label:xpath:.//label[@for='isActive']/preceding-sibling::input
toggle_label:xpath:.//label[@for='toggle']/preceding-sibling::input
list_dist_sccount:xpath:.//div[@class='rt-tbody']//div[@class='rt-tr-group']
dropdowns_printers:xpath:.//select[@name='${fieldName}']
facility_item_checkbox:xpath:.//label[@class='form-check-label']
delete_filter_btn:xpath:.//button[@name='delete']
multiple_filter:xpath:(.//select[@name='${field}'])['2'][2]
location_row:xpath:.//div[@class='rt-tr -odd']
header_dist_account:xpath:.//div[contains(text(),'${header}')]
message_field_blank_schedule:xpath:.//div[contains(@class, 'has-error')]//span
#message_field_blank_schedule:xpath:.//div[contains(@class, 'has-error')]//div[2]
select_dosage_form:xpath:.//select[@name='${fieldName}']
select_external_system:xpath:.//select[@name='${fieldName}']
#preffered_distributor_radiobutton_uat:xpath:.//div[contains(text(),'${fieldName}')]/preceding-sibling::div/div/input[contains(@id,'preferredDistributor')]
preffered_distributor_radiobutton:xpath://div[contains(text(),'${fieldName}')]/../../preceding-sibling::div/div/input[contains(@id,'preferredDistributor')]
#preferred_distributer_item_code_uat:xpath:.//div[contains(text(),'${fieldName}')]/following-sibling::div/div/div/input[contains(@id,'distributorItemCode')]
preferred_distributer_item_code:xpath://div[contains(text(),'${fieldName}')]/../../following-sibling::div/div/div/input[contains(@id,'distributorItemCode')]
select_item_facility:xpath://div[@class='col-3 system-facility-list']//ul/li[2]/div[contains(.,'${facilityName}')]
select_item_facility1:xpath://div[@class='col-3 system-facility-list']//ul/li[3]/div[contains(.,'${facilityName}')]
select_item_facility2:xpath://div[@class='col-3 system-facility-list']//ul/li[4]/div[contains(.,'${facilityName}')]
item_cost:xpath:.//input[@id='${name}']
chkbox_dist:xpath:.//div[contains(text(),'${name}')]/../../preceding-sibling::div/div/label[@class='form-check-label']
item_package_size:xpath://div[@class='rt-td'][contains(.,'${fieldName}')]/following-sibling::div//input[@id='packageSize']
prepack_checkbox:xpath://label[@for='${fieldName}']
bulk_item_id_mandatory:xpath://label[@for='${fieldName}'][contains(.,'* Bulk Item ID')]
prepack_conversion_factor:xpath://label[@for='${fieldName}'][contains(.,'* Prepack Conversion Factor')]
bulk_item_search:xpath:.//input[@id='bulkItemSearch']
unverified_item_search:xpath:.//input[@id='itemSearch']
bulk_item_click:xpath://div[@class='item-description']
page_heading_label:xpath:.//h3/b
edit_table_toggle:xpath:.//label[@for='${act}']/../input
new_distributor_radiobutton_at_facilitylevel:xpath://div[contains(text(),'${newDistributor}')]/../div/div/input
page_heading_edit_location:xpath:.//div[contains(@class,'breadcrumb-container')]//a[text()='Edit Location']
search_users_dest:xpath:.//input[@id='distributorSearch']
checkbox_users:xpath:.//label[contains(@for,'${flag}')]
items_RO_card:xpath:.//div[contains(@class,'card-items')]//div[@class='rt-table']//div[contains(@class,'rt-td')
items_RO_quantity:xpath:.//div[contains(@class,'card-items')]//input[@name='quantity']
items_PO_dashboard:xpath:.(//div[@class="column-title robotoBold d-center" and text()='${type}']/following::div[@class='tooltip-text'])//div[contains(text(),'%{Name}')]
text_box_bulk_item_id:css:.#bulkItemSearch
#button_FacilityEdit:xpath:.//div[contains(text(), '${facilityName}')]/following-sibling::div/div/button[@id='edit']
button_FacilityEdit:xpath:.//div[contains(text(), '${facilityName}')]
button_isaEdit:xpath:.//div[contains(text(), '${isaName}')]/../../../div[6]/button[contains(text(), 'Edit')]
button_editItemManagement:xpath:.//div[contains(text(), '${itemId}')]/following-sibling::div/div/button[@id='edit']
link_facilityItem:xpath:.//div[contains(text(), '${facility}')]
message_field_sched:xpath:.//div[contains(@class, 'has-error')]//div[2]
button_cancel_rotingRule:xpath:.//a[@id='${btnName}']
link_breadcrumb_routingRule:xpath:.//a[contains(text(), 'Pick Routing Rules')]
routing_priorities:xpath:(//div[contains(@class,'rt-tr -')]//div[@class='items'][contains(text(),'Priorities')])[1]
routing_destinations:xpath:(//div[contains(@class,'rt-tr -')]//div[@class='items'][contains(text(),'destinations')and not(contains(text(),'0 destinations'))])[1]
#Add_new_item_actions:xpath:.//a[contains(text(),'${fieldName}')]
Add_new_item_actions1:xpath:.//a[contains(text(),'${fieldName}')]
message_field_blank_distaccount:xpath:.//div[contains(@class, 'has-error')]/following::span
dropdown_facility:xpath:.//div[@class='form-group undefined']/select/option[contains(text(),'Earthquake')]
popup_message_schedule:xpath:.//div[text()='${msg}']
popup_message_sys_label:xpath://div[contains(text(), '${flag}')]
message_field_blank_facility:xpath:.//div[contains(@class, 'has-error')]//span
edit_location_field:xpath:.//div[@class='rt-tr']/div/div[contains(text(), '${fieldName}')]
value_edit_location:xpath:.//div[@class='form-group ']/input[@id='${fieldName}']
location_layout:xpath:.//li[@class='breadcrumb-item']/a[contains(text(),'Location & Inventory Management')]
rack_dropdown:xpath:.//select[@name='selectedRack']
rack_dots:xpath:.//div[@id='isa_info']/div/following::div/div/i[@id='${fieldName}']
add_rack:xpath:.//li[@class='d-flex justify-content-between']/div[contains(text(),'${facility}')]
racks_error_msg:xpath:.//ul[@class='d-flex justify-content-start align-items-start']/li
success_message_add_rack:xpath:.//div[@class='toast-body']
shelf:xpath:.//div[@name='selectedShelf']/div[contains(text(),'${field}')]
bin_area:xpath:.//div[@class='d-flex justify-content-start text-center bin-wid h-463']
shelf_actions:xpath:.//li[@class='d-flex justify-content-between']/div[contains(text(),'${actionName}')]
shelf_actions_text:xpath://div[contains(text(),'${actionName}')]
save_btn_applyoffset:xpath:.//div[@class='d-flex justify-content-end footer-btns pt-10']/button[@id='save']
click_shelf:xpath:.//div[@class="rolling-rack-items mb-4"]/div[2]
click_shelf1:xpath:.//div[@class="rolling-rack-items mb-4"]/div
shelf_dot:xpath:.//div[@class="rolling-rack-items mb-4"]/div[2]/div[2]
bin_dots:xpath:.//div[@id='isa_info']/div/following::div/div/i[@id='${fieldName}']/following::div[@class='bin-number'][${num}]
group_with_rightleftbin:xpath:.//div[contains(text(),'${field}')]
item_with_Assigned_location:xpath:(//div[5]/a[not(contains(text(),'0'))]/../../div[4]/div/div)[1]
uom_list_editbuttondisabled:xpath:.//div[@id='uom-edit']/button[contains(@class,'btn btn-link  mr-20 p-0 button-disabled')]
uom_list_editbuttonenabled:xpath:.//div[@id='uom-edit']/button[contains(@class,'btn btn-link  mr-20 p-0 addTextDecoration')]
location_rack_button:xpath:.//div[@class='rack-option d-flex mb-16']/i
location_rack_cyclecountdate_button:xpath:.//div[@class='menu-children h-24 w-14 ml-12']
location_calender_button:xpath:.//div[@class='${fieldName}']//button
location_date_value:xpath:.//div[contains(text(),'${fieldName}']
location_shelf_button:xpath:.//div[@name='selectedShelf']
location_shelf_button1:xpath:.//i[@id='shelf_actions']
location_shelf_cyclecountdate_button:xpath:.//li[3]//div[2]
location_date_field_value:xpath:.//input[@value='05/22/2020']
location_frame_hover:xpath:.//div[@name='selectedShelf']
location_rack_dropdown:xpath:.//select[@name='selectedRack']
location_rack_dropdown_option:xpath:.//select[@name='selectedRack']/option[1]
location_shelfs_field:xpath:.//div[contains(text(),'${fieldName}')]
location_shelfs_menu:xpath:.(//*[@id="shelf_actions"])[%{rownum}]
priority_trigger:xpath:.//a[@id='priority_trigger']
user_for_remoteorder:xpath:.//div[text()='${fieldName}']/../../..//div/label[contains(@for,'activeFlag')]
ro_uers_list:xpath:.//div[@class='ReactTable']//div[@class='rt-td']
checkbox_ControlCarouselISA:xpath:.//label[@for='controlCaraouselISA']
dropdown_labelPriority:xpath:.//a[@id='priority_trigger']/ul/li/input
value_labelPriority:xpath:.//label[@title='Package Share']
value_labelPriority_new:xpath:.//label[@title='${priorityName}']
distributorOptions_facility_checkbox:xpath:.//div[contains(text(),'${facility}')]/../../following-sibling::div/div/input[@name = '%{flagname}']/../label
adm_rounding_flag:xpath:.//input[@name='${fieldName}']/following-sibling::label
action_toggle_button_ro:xpath:.//div[contains(text(),'${item}')]/following-sibling::div//label[contains(@for, 'limitedOrderQuantity')]
input_field_ro:xpath:.//div[contains(text(),'${item}')]/following-sibling::div//input[contains(@id, 'maximumOrderQuantity')]
checkbox_destination_users_tab:xpath:.//div[@class='rt-tr -odd']/div[1]
verify_item_name_destination_users:xpath:.//div[@class='rt-tr -odd']/div[contains(text(),'${fieldName}']
all_checkboxes_therapeutic_class:xpath:.//label[@for='${fieldName}']
therapeutic_dropdown_item_screen:xpath:.//a[@id='${fieldName}']/ul/li/input
empty_unassigned_slot:id:selectedSlot
copy_facility_header:xpath:.//ul[@class='${fieldName}']/li
copy_facility_list:xpath:.//ul[@class='list-group p-0']/li[2]
empty_slot:xpath:.//div[@class='bin-info bin mr-16 selected-bin']//div[%{rownum}]
click_checkbox_Therapeuticclass_itemscreen:xpath:(//div[@class='infinite-scroll-component '])[1]/li/label[@title='${fieldName}']/input
label_tag:xpath://input[@id='labeltags-0']
#//span[@class='node-label'][contains(text(),'${fieldName}')]
popup_msg_delete_schedule:xpath:.//*[contains(text(),'${msg}')]
click_checkbox_setparticipatingfacility:xpath:(//div[@class='form-check '])/input/following-sibling::label
delete_productID:xpath://div[contains(text(),'${productID}')]/../../../div[7]/div/button[@id='edit']
ES_mapped_to_facility:xpath://div[contains(text(),'${facility}')]/../div[2]
facility_level:xpath:.//li[contains(text(),'${fieldName}')]
facility_level_dropdowns:xpath:.//select[@name='${fieldName}']/option
items_on_itemsTab:xpath://a[contains(text(),'${fieldName}')]/span
checkbox_pendingApprovalTab:xpath:.//label[@for='allCheckbox2']
mapped_locations:xpath:.//div[@class='popover-body']
manage_link:xpath:.//a[@class='btn-link']//span
first_toggle_scheduleRoutingRule:xpath:.//label[@for='allDays']/../../../../../div[1]/../following-sibling::div[1]
searchFieldFacility:xpath://input[@id='scheduleSearch']
noMatchingresult:xpath://div[text()='No Matching Results.']
facilityNameColumn:xpath://div[text()='Facility Name']
PISColumn:xpath://div[text()='PIS']
statusColumn:xpath:////div[text()='Status']
toggleButton:xpath://label[@class='switch-text']
activeStatus:xpath://span[text()='Active']
searchResultByFacility:xpath://button[text()='${facilityName}']
PISResult:xpath:(//div[@role='gridcell'])[2]
add_from_pis_columns:xpath:.//div[@class='rt-thead -header']//div[contains(text(),'${fieldName}')]
no_match_found:xpath://*[@id="item-id"]/div/div/span
edit_approved_computer:xpath:(.//button[contains(text(),'${fieldName}')])[1]
edit_approved_comp_modal:xpath://h3[contains(text(),'${pageTitle}')]
toggle_defineLabel:xpath://span[@class='switch']/input[@id='${toggle}']
edit_selected_button:xpath:.//button[contains(text(),'Edit Selected')]
button_location_number:xpath:.//div[@class='rt-td']/a[contains(text(),'1')]
#editlink_destination:xpath:.//div[contains(text(),'${destination}')]/following-sibling::div/button[@name='edit']
distributorname_POCard:xpath:.//input[@name='purchaseOrderDescription']
toggleButton:xpath://label[@for='toggle']
FacilityHeader:xpath://div[text()='Facility Name']
facilityHeaderSort:xpath://div[@class='rt-th rt-resizable-header -sort-asc -cursor-pointer']
PISHeader:xpath://div[text()='PIS']
StatusHeader:xpath://div[text()='Status']
toggleValue:xpath://input[@name='toggle']
addButtonFacility:xpath://button[@name='add']
distributorname_POCard:xpath:.//input[@name='purchaseOrderDescription']
item_in_destnation:xpath://div[contains(text(),'${data}')]
migration_status:xpath:.//div[contains(text(),'${Migrationcheck}')]/../../..//div[contains(text(),'%{Status}')]
updatedItemDescription:xpath:.//div[contains(@class,'item-description')][contains(text(),'${text}')]
popup_cancel_systemlabel:xpath://div[@class='modal-content']//span
link_preferdis:xpath:.//span[@title='${Name}']
action_button_new:xpath:.//button[text()='Cancel']
action_btn_isa:xpath:.//button[text()='${action}']
toggle_for_added_record:xpath://div[contains(text(),'${recordName}')]/../../../div[3]/div/span/label
main_menu_features_option:xpath://span[text()='${category}']/following::ul[1]//a/span[text()='%{feature}']
message_on_computer_popup:xpath:.//label[text()='${text}']
checkbox_computer:xpath:.//input[@id='${checkbox}']
txt_item_descriptions:xpath://div[contains(@class,'rt-tr -odd') or contains(@class,'rt-tr -even')]/div[5]			
cancel_prod:xpath:.//div[@class='d-flex justify-content-between']/..//button[@id='cancel']
flags_on_destination:xpath:.//label[contains(text(),'${text}')]
base_unit:xpath:.//div[@id='baseUOMKey']
base_unit_value:xpath:.//div[@class='modal-body']//div[contains(text(), '${value}')]
base_unit_dropdown:xpath:.//div[@class='css-kj6f9i-menu undefined react-select-dropdown__menu']
barCodevalueTextbox:xpath://input[@name='barcodeValue']
barCodeSearchClick:xpath://i[contains(@class,'icon-search-bold')]
sortingCursor:xpath://div[@class='rt-th rt-resizable-header -cursor-pointer'][contains(.,'Item ID')]
sortingCursonItem:xpath://div[@class='rt-th rt-resizable-header -sort-asc -cursor-pointer'][contains(.,'Item')]
sortingCursonItemAction:xpath://div[@class='rt-th rt-resizable-header -sort-asc -cursor-pointer'][contains(.,'Action')]
scanAnotherButton:xpath://button[@type='button'][contains(.,'Scan Another')]
unlinkButton:xpath://button[@type='button'][contains(.,'Unlink')]
barcode:xpath://p[contains(.,'')]
continueButton:xpath://button[@type='button'][contains(.,'Continue')]
linkButton:xpath://button[contains(@name,'link')]
relinkButton:xpath://button[@type='button'][contains(.,'Relink')]
resetButton:xpath:.//div/label/following::span[text()='Reset']
scanAnother:xpath://button[@type='button'][contains(.,'Scan Another')]
cantUnlinkMessage:xpath:(//div[contains(.,'Error : Cannot unlink preferred Product ID. Please')])[11]
editButton:xpath:(//button[@type='button'][contains(.,'Edit')])[1]
editISAButton:xpath:(//button[@class='btn btn-link'][contains(.,'Edit')])[1]
assignButton:xpath://button[@type='button'][contains(.,'Assign')]
saveAssignedLocation:xpath://button[contains(@class,'btn btn-primary pull-right')]
assignedColorPurple:xpath://button[@class='assign-bar border-0'][contains(.,'#')]
unavailableColorGrey:xpath://button[@class='unavailable-bar border-0'][contains(.,'#')]
availableColorGreen:xpath://button[@class='empty-bar border-0'][contains(.,'#')]
clickISAConfiguration:xpath://a[@class='tab-list-item '][contains(.,'ISA Configuration')]
verticalDividerNumber:xpath://input[contains(@name,'defaultBinDividersVerticalNumber')]
horizontalDividerNumber:xpath://input[contains(@name,'defaultBinDividersHorizontalNumber')]
invalidMessage:xpath://span[@class='help-block help-block-fixed'][contains(.,'Please enter a value greater than 0 and less than 100')]
clickBinOptions:xpath:(//i[@class='icon-more-bold'][contains(@id,'actions')])[7]
removeBin:xpath:.//div[contains(text(),'Remove Bin')]
lastMostBinSection:xpath:(//div[contains(@name,'selectedSlot')])[17]
assignLocationButton:xpath://button[@type='button'][contains(.,'Assign Location')]
saveButton:xpath://button[contains(@class,'btn btn-primary w-88')]
unassignButton:xpath://button[@type='button'][contains(.,'Unassign')]
unassignedYesButton:xpath://button[@type='button'][contains(.,'Yes')]
leftMostBin:xpath:(//div[contains(@name,'selectedSlot')])[3]
binOptionsLeftMost:xpath:(//i[@class='icon-more-bold'][contains(@id,'actions')])[3]
quantityAtHand:xpath://input[contains(@name,'inventoryQuantity')]
binProperties:xpath:(//div[contains(.,'Bin Properties')])[10]
isaNameVerify:xpath:(//div[contains(.,'NewISA2205')])[18]
rackVerify:xpath://i[contains(@id,'rack_actions')]
ShelfVerify:xpath://div[@class='fs-14 font-weight-bold shelf-color'][contains(.,'Shelf 1')]
binWidthBinProperties:xpath://input[contains(@name,'binWidth')]
verifyTickbarLeft:xpath://div[contains(@class,'menu-children h-24 w-16 ml-12')]
shelf1:xpath://div[@name='selectedShelf'][contains(.,'Shelf 1')]
clickShelfOptions:xpath:(//i[@class='icon-more-bold more-bin-icon'][contains(@id,'actions')])[1]
printShelfLables:xpath:(//div[contains(.,'Print Bin Labels')])[13]
printBinLables:xpath:(//div[contains(.,'Print Bin labels')])[10]
mergedBinOptions:xpath:(//i[@class='icon-more-bold'][contains(@id,'actions')])[10]
printBinLablesMerged:xpath:(//div[contains(.,'Print Bin labels')])[12]
slotOptions:xpath://i[contains(@id,'slot_actions')]
printSlotBinLables:xpath:(//div[contains(.,'Print Slot Label')])[11]
newAssignedLocaton:xpath:(//div[contains(@name,'selectedSlot')])[16]
editLocationButton:xpath://button[@type='button'][contains(.,'Edit')]
clickYesOnLocationChangeSave:xpath://button[@type='button'][contains(.,'Yes')]
mergeBins:xpath:(//div[contains(.,'Group with Right Bin')])[10]
totalInHandQuantity:xpath:(//div[contains(.,'Total On Hand Quantity =')])[8]
mergedBinNumberA:xpath://div[@class='bin-number'][contains(.,'8')]
mergedBinNumberB:xpath://div[@class='bin-number'][contains(.,'9')]
cancelYesButtonOnEditLables:xpath://button[@type='button'][contains(.,'Yes')]
cancelButtonOnEditLables:xpath://button[@type='button'][contains(.,'Cancel')]
addStandardLables:xpath://button[@type='button'][contains(.,'Add')]
standardLabelName:xpath://input[contains(@placeholder,'Label Name A')]
assignPriorities:xpath://input[contains(@class,'search')]
remove_Button:xpath:////button[@id='${fieldName}']
prefferedPrintLableBox:xpath://label[contains(@class,'form-check-label')]
noButtonForPrefferedBinLableIfPreexists:xpath://button[@type='button'][contains(.,'No')]
yesButtonForPrefferedBinLablesIfPreExists:xpath://button[@type='button'][contains(.,'Yes')]
editLablesBin:xpath:(//button[@type='button'][contains(.,'Edit')])[1]
editPrefferedPrintLable:xpath://label[contains(@for,'isPreferredLabel')]
verifyCategory:xpath://label[@class='d-block mt-8 robotoLight'][contains(.,'Bin Label')]
prePackCheckBox:xpath://label[contains(@for,'prepackFlag')]
setBulkItem:xpath://button[@type='button'][contains(.,'Set Bulk Item')]
selectBulkItem:xpath:(//div[contains(@class,'rt-td')])[3]
clickSaveOnSelectBulkItem:xpath://button[@class='btn btn-primary']
uncheckPrePackPopUpNoButton:xpath://button[@type='button'][contains(.,'No')]
PrePackConversionFactorTextBox:xpath://input[contains(@name,'prepackConversionFactor')]
invalidStringMessage:xpath://span[contains(.,'Should be 0.01 to 9999.99')]
uncheckPrePackPopUpYesButton:xpath://button[@type='button'][contains(.,'Yes')]
saveItemButtonPrePack:xpath://button[@type='button'][contains(.,'Save')]
cancelButton:xpath://button[@type='button'][contains(.,'Cancel')]
searchBulkItem:xpath://input[contains(@name,'search')]
nDCandDistributorPopup:xpath://div[contains(@class,'modal-body')]
okButton:xpath://button[@type='button'][contains(.,'OK')]
import_button:xpath://span[text()='Import Design']
maxlength_daily_Quantity:xpath://input[@name='maximumOrderQuantity']
import_button_file:xpath://div[@class='file-upload-btn w-112']
resetButtonBarcode:xpath://span[@class='btn-reset active'][contains(.,'Reset')]
no_item_found:xpath://h5[contains(text(),'No Results Found')]
addProductIDOnPage:xpath://button[@type='button'][contains(.,'Add Product ID')]
checkbox_batchEditFacility:xpath:.//div[contains(text(),'${priorityName}')]/../../following-sibling::div/div/input[@name='batchEnabledFlag']/../label
checkbox_autoReleaseEditFacility:xpath:.//div[contains(text(),'${priorityName}')]/../../following-sibling::div/div/input[@name='autoReleaseFlag']/../label
inputBox_batchEditFacility:xpath:.//div[contains(text(),'Receiving')]/../../following-sibling::div/div/input[@name='batchWaitMinutesQuantity']
editButtonOnItemManagementSearch:xpath://button[@type='button'][contains(.,'Edit')]
active_toggle_price_tagging:xpath:.//label[contains(@for,'${id}')]/../input
edit_button_priorityCode:xpath://span[contains(text(),'${priorityCode}')]/../../div[13]/button
adc_as_per_prioritycode:xpath://span[contains(text(),'${priorityCode}')]/../../div[7]/div/label
packageShare_modalBody:xpath:.//div[@class='modal-body']/span
toggle_itemManagement:xpath:.//input[@name='${toggle}']
toggle_itemManagement_1:xpath:.//label[@for='${toggle}']
prioritylist_Facility:xpath:.//div[@class='rt-tr-group']/div/div[1]
before_message:xpath:.//p[@class='robotoRegular fs-16']
checkbox_userDestination:xpath:.//input[@name='activeFlag']/../label
#link_edit_sanity:xpath:.//button[@id='edit']
link_edit_sanity:xpath:.//button[contains(text(),'${recordName}')]
error_on_WFA:xpath://div[text()='${text}']
assigned_slot:xpath:.//div[contains(@class,'unavailable')]
available_slot:xpath:.//div[contains(@class,'empty')][1]
bin_actions:xpath:.//i[@id='bin_actions']
add_hor_divider:xpath:.//div[contains(text(),'Add Horizontal Divider')]
add_vertical_divider:xpath:.//div[contains(text(),'Add Vertical Divider')]
error_msg_divider:xpath:.//div[@class='alert alert-warning alert-dismissible fade show flex-row align-items-baseline']/ul/li
text_FacilityDropdown:xpath:.//label[contains(text(), 'Facility the destination belongs to')]
text_packageShareFacilityDropdown:xpath:.//label[contains(text(), 'Destination is a Package Sharing Recipient')]
last_bin_actions:xpath:(.//i[@id='bin_actions'])[4]
third_bin_actions:xpath:(.//i[@id='bin_actions'])[3]
group_action:xpath:.//div[contains(text(),'${option}')]
bin_number:xpath:.//div[@class='bin-number']
test_ticbar_input:xpath:.//input[@id='tickBarInput']
test_ticbar:xpath:.//div[@class='form-group ']
bin_properties:xpath:.//h5[@class='modal-title']
bin_properties_isa_name:xpath:(.//div[@class='d-flex justify-content-between fs-14 mb-8'])[1]//div[2]
rack_info:xpath:(.//div[@class='d-flex justify-content-between fs-14 mb-8'])[2]
shelf_info:xpath:(.//div[@class='d-flex justify-content-between fs-14 mb-8'])[3]
other_location:xpath:(.//div[@class='bin-number'])[3]/parent::div/parent::div/div[1]/div
barcode_details:xpath://label[text()='${item}']/following-sibling::p
text_column_barcode:xpath://div[@class = 'rt-tr-group']/div/div/div/button[contains(text(), 'Link')]/../../preceding-sibling::div[${i}]
barcode_button:xpath://div[contains(@class,'footer-btns')]//button[text()='${action}']
barcode_rinlinking_msg:xpath://div[@class='modal-body']//div
barcode_popup_button:xpath://div[contains(@class,'modal-footer')]//button[text()='${action}']
shelf_print:xpath:.//div[@name='selectedShelf']/div[contains(text(),'Shelf 1')]
shelf_dots:xpath://i[@id='shelf_actions']
remove_bin:xpath:.//div[contains(text(),'Remove Bin')]
other_item_assigned:xpath:(.//div[contains(@class,'unavailable')])[1]
second_bin:xpath:(.//i[@id='bin_actions'])[2]
facility_dropdown_label:xpath:.//select[@name='facility']
online_help:xpath://a[@id='navbarDropdownHelpLink']
online_help_item:xpath://a[@role='menuitem']
online_help_header:xpath://h1[@class='noChapter']
##Added by BD Team############
max_order_qty_value:xpath:.//input[@id='maximumOrderQuantity-${index}']
results_dispense:xpath:.//div[@class='rt-tbody']//div[contains(@class,'rt-td')][${num}]/div/div
dropdown_labeltag_nomatches:xpath:.//span[@class='no-matches']
======================================================================================================================================
